---
- hosts: master, workers
  gather_facts: yes
  become_user: root
  become_method: sudo

  tasks:

    - name: patching /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      shell: |
        kube_interface=$(ip -o link show | awk -F': ' '{print $2}' | head -3 | tail -1)
        sudo cp /var/lib/kubelet/kubeadm-flags.env /var/lib/kubelet/kubeadm-flags.env.old
        ip=$(ip -f inet addr show $kube_interface | awk '/inet / {print $2}' | awk -F/ '{print $1}')
        sudo sed '${s/.$/ --node-ip '$ip'"/}' /var/lib/kubelet/kubeadm-flags.env.old | sudo tee /var/lib/kubelet/kubeadm-flags.env
        sudo systemctl daemon-reload
        sudo systemctl restart kubelet
      ignore_errors: no
      become: true
