packageList:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
keyUrl:
  - https://download.docker.com/linux/ubuntu/gpg
  - https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - https://baltocdn.com/helm/signing.asc
repoUrl:
  - deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ hostvars[inventory_hostname].ansible_distribution_release }} stable
  - deb https://apt.kubernetes.io/ kubernetes-xenial main # seems kubernetes-xenial does not depend of $(lsb_release -cs)
  - deb https://baltocdn.com/helm/stable/debian/ all main
#kubernetes:
#  domain: ako.avidemo.fr
#  ifApi: ens34
#  dockerUser: nic
#  dockerVersion: 5:19.03.8~3-0~ubuntu-bionic
#  podNetworkCidr: 10.244.0.0/16
#  version: 1.18.2-00
#  cniUrl: https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml # for Flannel
#  cniUrl: https://docs.projectcalico.org/manifests/calico.yaml # for calico
dockerK8sPackages:
  # - docker-ce-cli={{ dockerVersion }}
  - docker-ce={{ kubernetes.docker.version }}
  # - containerd.io
  - kubectl={{ kubernetes.version }}
  - kubelet={{ kubernetes.version }}
  - kubeadm={{ kubernetes.version }}
  - helm
#deploymentUrls:
#  - https://raw.githubusercontent.com/tacobayle/k8sYaml/master/k8sDeploymentBusyBoxFrontEndV1.yml
#  - https://raw.githubusercontent.com/tacobayle/k8sYaml/master/k8sDeploymentBusyBoxFrontEndV2.yml
#  - https://raw.githubusercontent.com/tacobayle/k8sYaml/master/k8sDeploymentBusyBoxFrontEndV3.yml
